// components/organism/WorkList.vue
﻿<template>
  <ul class="list">
    <li v-for="(work, i) of works" :key="`work-${i}-${work.id}`">
      <nuxt-link v-if="work.to" :to="work.to">
        <CardWork :work="work" />
      </nuxt-link>
    </li>
  </ul>
</template>
<script lang="ts" setup>
import { useWorks } from '~~/composables/data/useWorks';

const props = defineProps<{
  isPickedOnly?: boolean;
  excerptIds?: string[];
}>();

const works = useWorks().filter(work => (!props.excerptIds || !props.excerptIds.includes(work.id)) && (!props.isPickedOnly || work.isPicked));
</script>
<style lang="scss" scoped>
.list {
  padding: 0;
  margin: 0 0 30px;

  >li {
    border-bottom: 1px solid $color-gray;
    list-style: none;
    padding: 0;

    >a {
      text-decoration: none;
      display: block;
    }

    &:first-child {
      border-top: 1px solid $color-gray;
    }
  }
}
</style>

// src/components/WorkList/WorkList.tsx
import CardWork from '~/components/card/CardWork';
import SmartLink from '~/components/SmartLink';
import { getWorks } from '~/lib/data';
import * as s from './style.css';

export const WorkList = ({
  isPickedOnly,
  excerptIds,
}: {
  isPickedOnly?: boolean;
  excerptIds?: string[];
}) => {
  const works = getWorks().filter(
    (work) => !excerptIds?.includes(work.id) && (!isPickedOnly || work.isPicked),
  );

  return (
    <ul className={s.list}>
      {works.map((work, i) => (
        <li key={`work-${i}-${work.id}`}>
          {work.to && (
            <SmartLink to={work.to}>
              <CardWork work={work} />
            </SmartLink>
          )}
        </li>
      ))}
    </ul>
  );
};
