// components/organism/Hero.vue
﻿<template>
  <BlockHero>
    <h1 class="title">Arrrepentimiento</h1>
    <ul class="menu">
      <li v-for="link of links" :key="link.url">
        <a :href="link.url" target="_blank">{{ link.label }}</a>
      </li>
    </ul>
    <BlockImage>
      <img src="~/assets/images/collages/001.jpg" />
    </BlockImage>
  </BlockHero>
</template>
<script lang="ts" setup>
import { externalLinks as links } from '~/resources/links';
</script>
<style lang="scss" scoped>
.title {
  font-size: 64px;
  text-align: left;
  font-family: $font-rich;
  margin: 0;

  @include sp {
    font-size: 32px;
  }
}

.menu {
  padding: 0;
  margin: 0 0 80px;
  font-family: $font-rich;
  display: flex;

  >li {
    list-style: none;
    padding-right: 20px;
    font-size: 1.15rem;
  }

  @include sp {
    flex-direction: column;
  }
}
</style>

// src/components/Hero/Hero.tsx
// import collage from '~/assets/images/collages/001.jpg';
import { BlockHero } from '~/components/block';
import { externalLinks as links } from '~/resources/links';
import * as s from './style.css';

export const Hero = () => {
  return (
    <BlockHero>
      <div className={s.container}>
        <div className={s.inner}>
          <h1 className={s.title}>Arrrepentimiento</h1>
          <ul className={s.menu}>
            {links.map((link) => (
              <li key={link.url}>
                <a href={link.url} target="_blank" rel="noopener noreferrer">
                  {link.label}
                </a>
              </li>
            ))}
          </ul>
        </div>
      </div>
      {/* <BlockImage>
        <img src={collage} alt="Arrrepentimiento" />
      </BlockImage> */}
      <div className={s.image} />
    </BlockHero>
  );
};
