// pages/works.vue
﻿<template>
  <BlockMain>
    <OrganismHeading />
    <BlockTitle>Works</BlockTitle>
    <BannerBirthOfSignificance />
    <OrganismWorkList />
  </BlockMain>
</template>
<script lang="ts" setup>
import { useHtmlHeader } from '~~/composables/utils/useHtmlHeader';

useHtmlHeader({
  title: 'Works',
});

</script>

// src/pages/Works.tsx
import { BlockMain, BlockTitle } from '~/components/block';
import Heading from '~/components/organism/Heading';
import WorkList from '~/components/organism/WorkList';
import PageHead from '~/components/PageHead';

export default function Works() {
  return (
    <>
      <PageHead title="Works" />
      <BlockMain>
        <Heading />
        <BlockTitle>Works</BlockTitle>
        <WorkList />
      </BlockMain>
    </>
  );
}
