// components/organism/PostList.vue
﻿<template>
  <ul class="list">
    <li v-for="(post, i) of posts" :key="`post-${i}-${post.id}`">
      <nuxt-link v-if="post.to" :to="post.to">
        <CardPost :post="post" />
      </nuxt-link>
    </li>
  </ul>
</template>
<script lang="ts" setup>
import { usePosts } from "~~/composables/data/usePosts";
import { PostCategory } from "~~/types/post";

const props = defineProps<{
  isPickedOnly?: boolean;
  filterCategory?: PostCategory;
  excerptIds?: string[];
}>();

const posts = usePosts().filter(
  (post) =>
    (!props.excerptIds || !props.excerptIds.includes(post.id)) &&
    (!props.isPickedOnly || post.isPicked) &&
    (!props.filterCategory || post.categories.includes(props?.filterCategory))
);
</script>
<style lang="scss" scoped>
.list {
  padding: 0;
  margin: 0 0 30px;

  > li {
    border-bottom: 1px solid $color-gray;
    list-style: none;
    padding: 0;

    > a {
      text-decoration: none;
      display: block;
      color: $color-yellow;
      &:hover {
        color: $color-red;
      }
    }

    &:first-child {
      border-top: 1px solid $color-gray;
    }
  }
}
</style>

// src/components/PostList/PostList.tsx
import type { FC } from 'react';
import CardPost from '~/components/card/CardPost';
import SmartLink from '~/components/SmartLink';
import { getPosts } from '~/lib/data';
import type { PostCategory } from '~/types/post';
import * as s from './style.css';

type Props = {
  posts?: ReturnType<typeof getPosts>;
  isPickedOnly?: boolean;
  filterCategory?: PostCategory;
  excerptIds?: string[];
};

export const PostList: FC<Props> = ({
  posts: initialPosts,
  isPickedOnly,
  filterCategory,
  excerptIds,
}) => {
  const posts = (initialPosts || getPosts()).filter(
    (post) =>
      !excerptIds?.includes(post.id) &&
      (!isPickedOnly || post.isPicked) &&
      (!filterCategory || post.categories.includes(filterCategory)),
  );

  return (
    <ul className={s.container}>
      {posts.map((post, i) => (
        <li key={`post-${i}-${post.id}`}>
          {post.to && (
            <SmartLink to={post.to}>
              <CardPost post={post} />
            </SmartLink>
          )}
        </li>
      ))}
    </ul>
  );
};
